--[[© 2025 Bryce Carson.
  See the file README for more information on copying this software.

  This premake lua file was generated by Grok using the original `nwconfig` and
  `Makefile` from Noweb 3. It's purpose is to offer a configuration wizard to
  the user by calling `premake5`.
]]

--[[ Grok instructions: Your job is to read the strings in the nwconfig and
  Makefile files, and understand these as Makefile instructions. The makefile
  instructions are to be converted into a Premake5 Lua script which is
  interactive and will query the user for UNIX or Windows build configuration;
  use Premake5 documentation and facilities, like operating system agnosticism,
  to the benefit of the script.

  Grok output follows:

  -- premake5.lua
  -- Premake5 configuration wizard for Rammel (Noweb 3 derivative with Lua 2.5)
  -- Run with: premake5 vs2022   or   premake5 gmake2   or   premake5 xcode4 etc.
]]

-- Load the Wikipedia yesno module
yesno = load path.join("wikipedia", "yesno.lua")

print("Shall I utilize FORK subordinate processes? (Y/n)\nOtherwise I'll use SPAWN.")
if yesno(io.read("*line"), false) then
  pipe = "fork"
else
  pipe = "spawn"
end

if ui.YesNoDialog("Do you wish to continue?") then
  pipe = "fork"
else
  pipe = "spawn"
end

newoption {
   trigger = "install",
   description = "Run in interactive install-configuration mode first (recommended on fresh checkout)"
}

newoption {
   trigger = "bindir",
   value   = "PATH",
   description = "Directory where binaries (no, notangle, etc.) will be installed"
}

newoption {
   trigger = "texinputs",
   value   = "PATH",
   description = "Base directory for TeX inputs (where noweb.sty will be copied)"
}

newoption {
   trigger = "lib3",
   value   = "PATH",
   description = "Directory for Rammel private library/data (scripts, tools, etc.)"
}

newoption {
   trigger = "luaversion",
   allowed = { { "lua25", "Lua 2.5 (original Noweb 3 behaviour)" },
               { "lua30", "Lua 3.0 (experimental/transfer tests)" } },
   description = "Which Lua version to use for bootstrapping / transfer tests"
}

-- Default paths (will be overridden by interactive mode or command-line options)
local BINDIR     = _OPTIONS["bindir"]     or "/usr/local/bin"
local TEXINPUTS  = _OPTIONS["texinputs"]  or "/usr/local/share/texmf/tex/latex/local"
local LIB3       = _OPTIONS["lib3"]       or "/usr/local/lib/rammel"
local LUAVERSION = _OPTIONS["luaversion"] or "lua25"

if _OPTIONS["install"] or not (_OPTIONS["bindir"] or _OPTIONS["lib3"]) then
   print([[

   Welcome to Rammel (Noweb 3 derivative) configuration wizard
   ===========================================================

   This script will ask a few questions the first time you configure the build.
   You can always re-run with --install to change them later.
   ]])

   local function ask(question, default)
      io.write(question .. " [" .. default .. "]: ")
      io.flush()
      local answer = io.read():match("^%s*(.-)%s*$")
      if answer == "" then return default end
      return answer
   end

   local platform = os.host()
   if platform == "windows" then
      BINDIR    = ask("Install binaries to", "C:\\Rammel\\bin")
      TEXINPUTS = ask("TeX inputs base directory", "C:\\texlive\\texmf-local")
      LIB3      = ask("Rammel private library directory", "C:\\Rammel\\lib")
   else
      BINDIR    = ask("Install binaries to", "/usr/local/bin")
      TEXINPUTS = ask("TeX inputs base directory", "/usr/local/share/texmf/tex/latex/local")
      LIB3      = ask("Rammel private library directory", "/usr/local/lib/rammel")
   end

   local luv = ask("Lua version for normal build (lua25 / lua30)", "lua25")
   if luv == "lua30" then LUAVERSION = "lua30" else LUAVERSION = "lua25" end

   print("\nConfiguration summary:")
   print("   Binaries      -> " .. BINDIR)
   print("   TeX inputs    -> " .. TEXINPUTS)
   print("   Library dir   -> " .. LIB3)
   print("   Lua version   -> " .. LUAVERSION:upper())
   print("")
end

-- Normalise paths for the current OS
if os.host() == "windows" then
   BINDIR    = BINDIR:gsub("/", "\\")
   TEXINPUTS = TEXINPUTS:gsub("/", "\\")
   LIB3      = LIB3:gsub("/", "\\")
   P         = "\\"
   E         = ".exe"
   NUL       = "NUL"
else
   P         = "/"
   E         = ""
   NUL       = "/dev/null"
end

-- Create the workspace
workspace "Rammel"
   configurations { "Debug", "Release" }
   location "build"

   filter "system:windows"
      platforms { "x64" }
   filter {}

project "rammel_tools"
   kind "StaticLib"
   language "C"
   targetdir "$(LIB3)%{P}tools"
   objdir "build/obj/tools"

   files { "tools/*.c", "tools/*.h" }
   includedirs { "cii/include" }

   filter "configurations:Debug"
      defines { "DEBUG" }
      symbols "On"
   filter "configurations:Release"
      defines { "NDEBUG" }
      optimize "On"

project "rammel_cii"
   kind "StaticLib"
   language "C"
   targetdir "$(LIB3)%{P}cii"
   objdir "build/obj/cii"

   files { "cii/src/*.c", "cii/include/*.h" }
   defines { "CIIMAXALIGN=4" }   -- adjust if needed on exotic platforms

project "lua25"
   kind "StaticLib"
   language "C"
   targetdir "$(LIB3)%{P}lua-2.5"
   objdir "build/obj/lua25"

   files { "lua-2.5/src/*.c", "lua-2.5/src/*.h" }
   removefiles { "lua-2.5/src/lua.c", "lua-2.5/src/luac.c" }

project "lua30"   -- optional, only built for transfer tests
   kind "StaticLib"
   language "C"
   targetdir "$(LIB3)%{P}lua-3.0"
   objdir "build/obj/lua30"

   files { "lua-3.0/src/*.c", "lua-3.0/src/*.h" }
   removefiles { "lua-3.0/src/lua.c", "lua-3.0/src/luac.c" }

   filter { "options:luaversion=lua30" }
      buildoptions { "-DLUA_30" }

-- Custom commands that replace the old recursive make mess
newaction {
   trigger     = "bootstrap",
   description = "Build the minimal noweb tools needed for tangling",
   execute     = function ()
      os.executef("premake5 --file=%s vs2022", _MAIN_SCRIPT)  -- or gmake2 etc.
      os.execute("cd build && ninja rammel_tools rammel_cii "..(LUAVERSION=="lua30" and "lua30" or "lua25"))
   end
}

-- Main tangling / code generation (replaces the huge 'all' target)
newaction {
   trigger     = "all",
   description = "Generate all code, scripts and styles (normal build)",
   execute     = function ()
      local tools  = LIB3 .. P .. "tools"
      local lua_lib = LIB3 .. P .. (LUAVERSION == "lua30" and "lua-3.0" or "lua-2.5")

      local function tangle(dir, extra_opts)
         local opts = extra_opts or ""
         local cmd = string.format('cd %s && make NOTANGLE=more TANGLEOPTS="%s" OUTPUT=%s%s%s TOOLS=%s LUA=..%slua-2.5 LUALIB=%s',
                                   dir, opts, LIB3, P, dir, tools, P, lua_lib)
         print("==> " .. cmd)
         os.execute(cmd)
      end

      -- Ensure lib directories exist
      os.mkdir(path.join(LIB3, "c"))
      os.mkdir(path.join(LIB3, "lua"))
      os.mkdir(path.join(LIB3, "tex"))

      tangle("c",   '| nocond lua2 | nocond | ' .. tools .. P .. 'markup | ' .. tools .. P .. 'nt')
      tangle("lua", '| nocond lua2 | ' .. tools .. P .. 'markup | ' .. tools .. P .. 'nt')
      tangle("tex", '')
   end
}

newaction {
   trigger     = "install",
   description = "Install binaries and TeX styles",
   execute     = function ()
      print("Installing binaries to " .. BINDIR)
      os.copyfile(path.join(LIB3, "c", "no", E), -- E := extension?
                  BINDIR, "no", E) -- E := extension?
      os.copyfile(LIB3, "c", "nwmtime", E, -- E := extension?
                  BINDIR, "nwmtime", E) -- E := extension?

      print("Installing scripts")
      os.copydir(path.join(LIB3, "lua"), BINDIR, "*.lua")

      print("Installing TeX styles")
      local texdest = path.join(TEXINPUTS, "latex", "misc")
      os.mkdir(texdest)
      os.copyfile(path.join(LIB3, "tex", "noweb.sty"),
                  path.join(texdest, "noweb.sty"))
      os.copyfile(path.join(LIB3, "tex", "nwmac.tex"),
                  path.join(TEXINPUTS, "generic", "misc", "nwmac.tex"))
   end
}

newaction {
   trigger     = "clean",
   description = "Clean generated files",
   execute     = function ()
      os.rmdir(LIB3)
      os.rmdir("build")
   end
}

-- Simple helper to expose the chosen variables to generated makefiles / VS projects
solution "Rammel"
   defines {
      string.format('BINDIR="%s"', BINDIR),
      string.format('TEXINPUTS="%s"', TEXINPUTS),
      string.format('LIB3="%s"', LIB3),
      string.format('PLATFORM="%s"', (os.host()=="windows") and "win" or "unix"),
      'P="'..P..'"',
   }
