#+TITLE: Rammel
#+AUTHOR: Bryce Carson

* Grok help                                                         :ARCHIVE:
*Minimal changes needed:*

- Use POSIX-style paths (=/=) and Unix commands (=rm=, =mkdir=, etc.).
  No accommodation for Windows =\= separators required.

- Detect environment if needed:

  #+begin_src make
  ifeq ($(OS),Windows_NT)
    # optional Windows-specific rules
  else
    # POSIX (MSYS2)
  endif
  #+end_src

- For executables: add =.exe= suffix when targeting native MinGW builds
  (e.g., =TARGET = myprog$(EXE)= where =EXE=.exe= on Windows).

MSYS2 make in Git for Windows SDK behaves like Unix make.

* Dependencies                                                      :ARCHIVE:
On Windows, building requires the full /Git for Windows SDK/ installed, not just
/Git for Windows/. This allows Windows users to use MSYS2 to build Arch
packages, in particular the =make= package with Guile support. =make= on MSYS2
enables native Windows development using GNU Make makefiles without compromising
on syntax or overusing text replacement macros to provide compatibility with
Windows path separators and other oddities.

Everything I was writing in Premake is moving back into Make, but with the Guile
feature so I can rewrite the helper functions I wrote in Lua in Guile and use
that to simplify the makefile.

Make supports Guile Scheme as an embedded extension language since version 4.0,
but many distributions do not build Make with this feature by default.

*** Fedora
Fedora no longer builds /GNU make/ with Guile enabled by default, so I needed to
rebuild the package with the Guile feature enabled.

#+begin_src bash
  dnf download --srpm make
  dnf install 'pkgconfig(guile-3.0)' perl# perhaps also perl-devel and guile-devel
  rpmbuild -ba make.spec --with guile
  rpmbuild -ba --with guile
#+end_src

*** Arch & Windows (with the /Git for Window SDK/)
The full SDK version of Git for Windows shall be required, as the new
makefile utilizes GUILE to simplify some build steps that were
difficult.

1. =pacman -S --needed base-devel guile-devel=.
2. =git clone https://github.com/msys2/MSYS2-packages.git && cd MSYS2-packages/make=.
3. Edit =PKGBUILD=: remove =--without-guile= (or add =--with-guile=) from =configure= line.
4. =makepkg -s --noconfirm=.
5. =pacman -U make-*.pkg.tar.zst=.

* About
This is a working file only. It is not documentation for Rammel.

#+begin_quote
With this change you will have .cfg files for configuration and shared
functions, .nws files for stages and internal filters, and extensionless files
for commands.
#+end_quote


It's my goal to edify myself by translating into Lua 5.5 the filters and stages
which were previously translated by Zitzelsberger from lua2.5+nw into Lua 3.

I will be calling this derived work Rammel. In the future, especially if all
development goals are met, I'll send Ramsey another postcard to ask about
calling it noweb and getting the changes merged.

** noweb version 3 uses a customized version of Lua 2.5.1       :note:readme:
The introductory content of the noweb version 3 README describes what noweb
version 3 is, in brief, and why it uses Lua. It also has some cautionary content
about the futility of maintaining noweb version 3.

#+begin_quote
This is Noweb 3.  Noweb 3 is a reimplementation of Noweb using
a customized version of Lua 2.5.  Noweb 3 was conceived and
implemented in 1996 to solve two problems:

  - Noweb 2 was hard to install.
  - Without Icon, Noweb 2 can slow and hard to extend.

Advances in software and hardware have made these problems irrelevant:
Linux distributions and OSX ports have shifted installation costs from
the end user to the distribution maintainers, and those same
distributions have made it easy to build on fast Icon code instead of
slow Awk code.  Noweb 3 retains some value; it is more flexible and
easier to extend than Noweb 2, but in Fall 2015, as these words are
being written, maintaining Noweb 3 makes no sense.  In a just world,
Noweb 3 would be completely rewritten using Lua 5.  But that won't
happen.

I have used Noweb 3 in production for some years, but I continue to
call this distribution "alpha quality."  Alpha versions are numbered
by date; for example, the first version to tangle and weave itself was
alpha980616.  This alpha version is made available from github
(nrnrnr/noweb3) so that those who wish to play with Noweb 3 can do so.
#+end_quote

The reason I am interested in noweb version 3 is because (all?) filters and
pipeline stages are implemented in Lua, rather than Icon. I don't want to learn
Icon to hack on noweb version 2 filters, and it really isn't ideal to implement
advanced customizations or hacks in AWK.

* Lua sources
The lua sources of Rammel are tangled from a single web, combined from all the
webs that previously existed. The =all= target would run by default in the
original makefile.

#+begin_quote
LIB3 is where Noweb 3 scripts and configuration files go.
#+end_quote

#+begin_src lua
  NOTANGLE="more"
  TANGLEOPTS=" | $(NOCOND) lua2 | $(LIB3)/tools/markup | $(LIB3)/tools/nt"
  --[[CPIF is initially the symbol for simple stdout redirection to a file.]]
  OUTPUT=_OPTIONS["OUTPUT"]
#+end_src

Below is the original =src/lua/Makefile=.

#+begin_src makefile
  $(guile $(load ../nwconfig.scm))

  $(guile $(load lua-outputs.scm))

  CONFIG="$(guile (path-expand '(pipes.cfg sys.cfg noweb.cfg util.cfg list.nws set.nws) output))"
  FILTERS="$(guile (path-expand '(cat.nws stripconds.nws xchunks.nws lines.nws) output))"
  STAGES="$(guile (path-expand '(totex.nws tohtml.nws noidx.nws elide.nws unmarkup.nws) output)) $(FILTERS)"
  SCRIPTS="$(guile (path-expand '(tangle weave) output))"

  all: $(CONFIG) $(STAGES) $(SCRIPTS)

  test: $(CONFIG) $(STAGES) $(SCRIPTS)
  	@echo 'write("Scripts load from .\n")' | NWPATH=. no
  	@echo 'argv = {"-internaldefaults", "-n", "-html", "/dev/null"}; do_nwfile("weave.nws"); write("Null weave OK.\n")' | NWPATH=. no
  	@echo 'argv = {"-internal", "test.nw"}; do_nwfile("tangle.nws"); write("Null tangle OK.\n")' | NWPATH=. no

  htmltest: $(CONFIG) $(STAGES) $(SCRIPTS)
  	@echo 'testfile("/home/nr/www/noweb/index.html")' | NWPATH=. no

  clean:

  clobber: clean
  	-$(RM) $(CONFIG) $(FILTERS) $(STAGES) $(SCRIPTS) 2>$(NUL)

  install: $(SCRIPTS) $(CONFIG) $(STAGES)
  	for i in $(CONFIG) $(STAGES); do sed 's@|LIBDIR|@$(LIB2)@g' $$i > $(LIB3)/$$i;                 done
  	for i in $(SCRIPTS);          do cp                         $$i   $(LIB3)/`basename $$i .nws`; done

  # Produce rules
  "$(guile (map (lambda (w) (path-expand (cpif (notangle tangle-options w) w) output)) '(list.nw set.nw totex.nw tohtml.nw noidx.nw elide.nw unmarkup.nw cat.nw stripconds.nw xchunks.nw lines.nw tangle.nw weave.nw)))"
  "$(guile (path-expand (cpif (notangle tangle-options config.nw :root pipes.cfg) pipes.cfg) output))"
  "$(guile (path-expand (cpif (notangle tangle-options config.nw :root sys.cfg) sys.cfg) output))"
  "$(guile (path-expand (cpif (notangle tangle-options config.nw :root noweb.cfg) noweb.cfg) output))"
  "$(guile (path-expand (cpif (notangle tangle-options config.nw :root util.cfg) util.cfg) output))"

  noidx.tex: noidx.nw
  	noweave -delay -x -filter 'elide hackers:*' noidx.nw > noidx.tex
#+end_src

Everything that didn't use a root (see the following list) used the default root
of ~<<*>>=~, per the defaults of Noweb 2 itself.

- list.nw
- set.nw
- totex.nw
- tohtml.nw
- noidx.nw
- elide.nw
- unmarkup.nw
- cat.nw
- stripconds.nw
- xchunks.nw
- lines.nw
- tangle.nw
- weave.nw

Among the original, separate noweb files four roots were tangled from
=config.nw=: =pipes.cfg=; =sys.cfg=; =noweb.cfg=; =util.cfg=.

#+begin_src lua :noweb-ref "tangle noweb lua scripts"
  local notangle = path.getabsolute("nt", _OPTIONS["libexec"])
  local notangle_options = ""
  local cpif = ">"--could be changed to the cpif utility
  local function tangle(notangle, notangle_options, cpif, target, root) do
    if root then
      local cpif_root = string.format("-R%s %s %s", root, cpif, root)
    elseif
      local cpif_root = string.format("%s %s", cpif, root)
    end
    os.executef("%s lua.nw %s %s", notangle, notangle_options, cpif_root, target)
  end
  for target in { "pipes.cfg", "sys.cfg", "noweb.cfg", "util.cfg" } do
    tangle(notangle, notangle_opts, cpif, target, target)
  end
  local scripts = {
    "list.nws",
    "set.nws",
    "totex.nws",
    "tohtml.nws",
    "noidx.nws",
    "elide.nws",
    "unmarkup.nws",
    "cat.nws",-- apparently not installed anywhere
    "stripconds.nws",
    "xchunks.nws",
    "lines.nws",

    "tangle",
    "weave"
  }
  for lua_script in scripts do
    tangle(notangle, notangle_opts, cpif, lua_script)
  end

  local config = { "pipes.cfg", "sys.cfg", "noweb.cfg", "util.cfg", "list.nws", "set.nws" }

  -- FIXME: The filters cat, stripconds, xchunks, and lines are missing.
  local configurations_and_stages = {
    -- Lua+nw, but with a different intention.
    "pipes.cfg",
    "sys.cfg",
    "noweb.cfg",
    "util.cfg",
    "list.nws",
    "set.nws",
    "totex.nws",
    "tohtml.nws",
    "noidx.nws",
    "elide.nws",
    "unmarkup.nws"
  }

  -- Overwrite the tangled nws files with their edited versions. This is
  -- alternative to calling sed.
  for configuration_or_stage in configurations_and_stages do
    local edited = io.output(io.tmpfile())
    for line in io.lines(configuration_or_stage) do
      io.write(string.gsub(line, "|LIBDIR|", "$(LIB2)"))
    end
    edited:close()
    os.copyfile(edited, path.getabsolute(i, "build/src/lua/"))
  end
#+end_src

#+begin_src lua :noweb-ref "install noweb lua scripts"
  for f in { script, configuration_or_stage } do
    os.copyfile(path.getabsolute(f, "build/src/lua/"),
                path.getabsolute(f, _OPTIONS["LIB3"]))
  end
#+end_src

** Formal Tests
Two tests were defined in the original Makefile, one for the functionality of the Lua sources and one for the HTML.

#+begin_src makefile
  test: $(CONFIG) $(STAGES) $(SCRIPTS)
        @echo 'write("Scripts load from .\n")' | NWPATH=. no
        @echo 'argv = {"-internaldefaults", "-n", "-html", "/dev/null"}; do_nwfile("weave.nws"); write("Null weave OK.\n")' | NWPATH=. no
        @echo 'argv = {"-internal", "test.nw"}; do_nwfile("tangle.nws"); write("Null tangle OK.\n")' | NWPATH=. no

  htmltest: $(CONFIG) $(STAGES) $(SCRIPTS)
        @echo 'testfile("/home/nr/www/noweb/index.html")' | NWPATH=. no
#+end_src

The first test ensures that =no= can load scripts from the current directory.
The envvar =NWPATH= was set to =.=, the current directory, and =no= called with
it standard input from the =@echo= lines.

#+begin_src lua
  write("Scripts load from .\n");
  argv = { "-internaldefaults", "-n", "-html", "/dev/null" }; do_nwfile("weave.nws"); write("Null weave OK.\n");
  argv = { "-internal", "test.nw" }; do_nwfile("tangle.nws"); write("Null tangle OK.\n");
#+end_src

* C sources
To build /no/ and /nwmtime/, the two projects that comprise the Rammel, H and C
files must first be tangled from their noweb sources.

** Define a Guile Scheme interface to tangle headers and sources with options and also varying between =notangle= or =no tangle=
This was converted from Lua to Guile Scheme by Grok.

#+begin_src scheme
  (use-modules (ice-9 format) (ice-9 ftw) (ice-9 textual-ports) (srfi srfi-1) (srfi srfi-13))

  (define (tangle-c-or-h-file noweb-file-basename
                              #:key root output-file redirection-op tangleopts version specifier)
    (let* ((src-dir "../src/c")
           ;; Determine output file
           (output-file
            (or output-file
                (if (not root)
                    (string-append src-dir "/" noweb-file-basename ".c")
                    (string-append src-dir "/" noweb-file-basename ".h")))))

      ;; Ensure output looks correct
      (when (not root)
        (unless (string-suffix? ".c" output-file)
          (format #t "Warning: ~a is not a .c file!~%" output-file)))
      (when root
        (unless (string-suffix? ".h" output-file)
          (format #t "Warning: ~a is not a .h file!~%" output-file)))

      ;; Build noweb_file path
      (let* ((noweb-file (if (absolute-file-name? noweb-file-basename)
                             noweb-file-basename
                             (string-append src-dir "/"
                                            (if (string-suffix? ".nw" noweb-file-basename)
                                                noweb-file-basename
                                                (string-append noweb-file-basename ".nw"))))))

        ;; Handle specifier (nocond-like chunk rewriting)
        (let ((translated-file
               (if specifier
                   (let* ((lines (call-with-input-file noweb-file
                                   (lambda (p) (string-split (get-string-all p) #\newline))))
                          (new-lines
                           (map (lambda (line)
                                  (let ((m (string-match
                                            (string-append "^<<(.+) *\\\\(\\(" specifier "\\)\\)>>=$")
                                            line)))
                                    (if m
                                        (string-append "<<" (match:substring m 1) ">>=")
                                        line))))
                           lines)))
                   (let ((tmp (tmpnam)))
                     (call-with-output-file tmp
                       (lambda (p) (for-each (lambda (l) (format p "~a~%" l)) new-lines)))
                     tmp))
               noweb-file)))

        ;; Build command
        (let* ((root-opt (if root (format #f "-R\"~a\"" root) ""))
               (redir (or redirection-op ">"))
               (tangle-opts (or tangleopts ""))
               (cmd (format #f "~a ~a -L\"#line %L \\\"~a.nw\\\"%N\" ~a ~a ~a"
                            translated-file tangle-opts noweb-file-basename
                            root-opt redir output-file)))

          (cond
           ((not (or (eq? version 2) (eq? version 3)))
            (error "version must be 2 or 3"))
           ((= version 2)
            (system (string-append "notangle" cmd)))
           (else
            (system (string-append "no tangle" cmd))))

          (when (and (string? translated-file) (not (equal? translated-file noweb-file)))
            (delete-file translated-file))))))

  (display "Generating H sources with bundled Noweb (version 2)...")
  (define headers
    '("cargs" "columns" "cpif" "env-lua" "errors" "fromascii"
      "getline" "ipipe" "ipipe-lua" "lua-help" "lua-main"
      "markparse" "markup" "match" "misc-lua" "modtrees"
      "modules" "mpipe" "mpipe-lua" "notangle" "noweb-lua"
      "nwbuffer" "nwprocess" "nwtime" "precompiled" "recognize"
      "stages" "strsave" "sys" "util" "xpipe" "xpipe-lua"))
  (for-each (lambda (header)
              (tangle-c-or-h-file header #:root "header" #:version 2))
            headers)

  (display "Generating C sources with bundled Noweb (version 2)...")
  (define sources
    '("columns" "cpif" "errors" "env-lua" "finduses" "fromascii"
      "getline" "ipipe" "ipipe-lua" "lua-help" "lua-main" "main"
      "markup" "markparse" "misc-lua" "modtrees" "modules"
      "mpipe" "mpipe-lua" "notangle" "noweb-lua" "nwbuffer"
      "nwprocess" "nwmtime" "nwtime" "recognize" "stages"
      "strsave" "sys" "util" "xpipe" "xpipe-lua"))
  (for-each (lambda (source)
              (tangle-c-or-h-file source #:version 2))
            sources)

  (tangle-c-or-h-file "nwbuffer" #:root "nwbuffer-lua.c" #:output-file "../src/c/nwbuffer-lua.c" #:version 2)
#+end_src

** Define a Lua interface to tangle headers and sources with options and varying =notangle= or =no tangle=
A very handsome, little Lua function was written to tangle H and C sources given
a Lua table and some optional arguments.

#+begin_src lua :noweb-ref "tangle sources"
  -- tangle_c_or_h_file("example") :: notangle example.nw > example.c# tangle the default * module.
  function tangle_c_or_h_file (noweb_file_basename, root, output_file, redirection_op, tangleopts, version, specifier)
    if not root and not output_file then
      output_file = path.join("../src/c", string.format("%s.c", noweb_file_basename))
      if not path.iscfile(output_file) then printf("Path: %s is erroneously not a C file!", output_file) end
    end
    if not output_file then
      output_file = path.join("../src/c", string.format("%s.h", noweb_file_basename))
      if not path.iscppheader(output_file) then printf("Path: %s is erroneously not an H file!", output_file) end
    end

    --[[In one call the noweb_file_basename is actually an absolute path.
      "If trailing is an absolute path, then the leading portion is ignored, and the
      absolute path is returned instead (see below for examples)."]]
    noweb_file = path.join("../src/c", noweb_file_basename)
    if not path.isabsolute(noweb_file) then
      --[[When noweb_file is contstructed from a real basename, the noweb_file
        must be given an extension.]]
      noweb_file = path.replaceextension(noweb_file, "nw")
    end

    if specifier then
      --[[Read the lines of the file, one at a time, outputting them to tempfile; as
        --the iteration proceeds, the provided chunk specifier will be used to modify
        --chunk definitions as they're written, emulating nocond.]]
      noweb_file_lines = io.readfile(noweb_file)
      for line, line_number in next, string.explode(noweb_file_lines, "\n") do
        captures = string.match(line, "^<<(.+) *\\(\\("..specifier.."\\)\\)>>=$")
        if (captures) then
          noweb_file_lines[line_number] = string.format("<<"..captures..">>=")
        end
      end
      translated_file = io.tmpfile()
      io.writefile(translated_file, table.concat(noweb_file_lines, "\n"))
    else
      translated_file = noweb_file
    end

    if root then
      root = string.format("-R\"%s\"", root)
    else
      root = ""
    end

    if not redirection_op then
      redirection_op = ">"
    else-- I only ever use "a+" to indicate that I intend to append.
      redirection_op = ">>"
    end

    if not tangleopts then
      tangleopts = ""
    elseif tangleopts and not version == 2 then
      error("When version is 3 tangleopts must not be provided.", 2)
    end

    -- The leading space character is intentional.
    cmd = string.format([[ %s %s -L"#line %%L "\"%s.nw"\"%%N" %s %s %s]],
      translated_file,
      tangleopts,
      noweb_file_basename,
      root,
      redirection_op,
      output_file)
    if not (version == 2 or version == 3) then
      error("The argument version must be the number 2 or 3!", 2)
    elseif version == 2 then
      cmd = "notangle"..cmd
    else
      cmd = "no tangle"..cmd
    end
    verbosef("    %s", cmd)
    os.execute(cmd)
  end
#+end_src

*** Tangle the H files.

#+begin_src lua :noweb-ref "tangle sources"
  verbosef("Generating H sources with bundled Noweb (version 2)...")
  for index, header in pairs({
      "cargs",       "columns",
      "cpif",        "env-lua",
      "errors",      "fromascii",
      "getline",     "ipipe",
      "ipipe-lua",   "lua-help",
      "lua-main",    "markparse",
      "markup",      "match",
      "misc-lua",    "modtrees",
      "modules",     "mpipe",
      "mpipe-lua",   "notangle",
      "noweb-lua",   "nwbuffer",
      "nwprocess",   "nwtime",
      "precompiled", "recognize",
      "stages",      "strsave",
      "sys",         "util",
      "xpipe",       "xpipe-lua"
  }) do tangle_c_or_h_file(header, "header") end

  verbosef("Generating C sources with bundled Noweb (version 2)...")
  for index, source in pairs({
      "columns",   "cpif",
      "errors",    "env-lua",
      "finduses",  "fromascii",
      "getline",   "ipipe",
      "ipipe-lua", "lua-help",
      "lua-main",  "main",
      "markup",    "markparse",
      "misc-lua",  "modtrees",
      "modules",   "mpipe",
      "mpipe-lua", "notangle",
      "noweb-lua", "nwbuffer",
      "nwprocess", "nwmtime",
      "nwtime",    "recognize",
      "stages",    "strsave",
      "sys",       "util",
      "xpipe",     "xpipe-lua"
  }) do tangle_c_or_h_file(source) end

  tangle_c_or_h_file("nwbuffer", "nwbuffer-lua.c", "../src/c/nwbuffer-lua.c")
#+end_src

** no
/no/ is the main program distributed with the Rammel package.

#+begin_src lua :noweb-ref "define the projects for no and nwmtime"
  project "no"
  kind "ConsoleApp"
  --[[Does the system's C library have tempnam? If so, the user should add
  "-DTEMPNAM"; FIXME: I should detect this and automatically add a defines.
  However, the manual page for the function advised to NEVER use the function,
  suggesting mkstemp or tmpfile instead.]].
  buildoptions { _OPTIONS["COMPILER_FLAGS_EXTRA"] }--XCFLAGS
  includedirs {
    "../vendor/lua-2.5",
    "../vendor/cii/include",
    "../src/c"
  }
  files {
    "../src/c/*.c",
    "../vendor/cii/src/*.c"
  }
  removefiles {
    "../src/c/nwmtime.c",
    "../vendor/cii/src/mem.c"
  }
  if os.target() == "linux" then
    defines {
      "PLATFORM=\"unix\"",
      "nw_unix=1",
      "POSIX=1"
    }
  else
    defines {
      "PLATFORM=\"nt\"",
      "nw_nt",
      "WIN32=1"
    }
  end
  links { "lua" }
#+end_src

** nwmtime
The other executable to create is /nwmtime/, which is used to gather the
modification time of things within a noweb pipe.

#+begin_src lua :noweb-ref "define the projects for no and nwmtime"
  project "nwmtime"
  defines { "POSIX=1" }
  includedirs {
    -- "../vendor/lua-2.5",
    "../vendor/cii/include",
    "../src/c",
  }
  files {
    "../src/c/nwmtime.c",
    "../src/c/getline.c",
    "../src/c/columns.c",
    "../src/c/errors.c",
    "../vendor/cii/src/except.c",
    "../vendor/cii/src/assert.c",
  }
  kind "ConsoleApp"
  if os.target() == "linux" then
    defines { "PLATFORM=\"unix\"", "nw_unix" }
  else
    defines { "PLATFORM=\"nt\"", "nw_nt" }
  end
#+end_src

* Vendored sources
* Tests
* Guile-validated options
The options for configuring Rammel are the same as configuring noweb version 3.

#+begin_src scheme :tangle src/options.scm
  (use-modules (ice-9 format) (srfi srfi-1))

  (define options (make-hash-table))

  (define (option sym default description validator category)
    (hash-set! options sym
               (list (cons 'value default)
                     (cons 'default default)
                     (cons 'description description)
                     (cons 'validator validator)
                     (cons 'category category)))
    default)

  (define (option-get sym)
    (let* ((entry (hash-ref options sym))
           (val (assq-ref entry 'value)))
      (if (and entry val)
          val
          #f)))

  (define (option-set sym val)
    (let ((entry (hash-ref options sym)))
      (when entry
        (hash-set! options sym
                   (assq-set! entry 'value val))
        val)))

  (define (option-validate sym)
    (let* ((entry (hash-ref options sym))
           (val (and entry (assq-ref entry 'value)))
           (validator (and entry (assq-ref entry 'validator))))
      (if (not validator)
          #t
          (let ((check (lambda (v)
                         (cond ((procedure? validator) (validator v))
                               (else #f)))))
            (if (list? val)
                (every check val)
                (check val))))))

  (define (option-print)
    (hash-for-each
     (lambda (sym entry)
       (format #t "~a (~a): ~a = ~s~%" sym (assq-ref entry 'category)
               (assq-ref entry 'description) (assq-ref entry 'value)))
     options))

  ;; Example definitions (fixed/updated from provided)
  (option 'PIPE "fork"
          "How to run pipelines of programs and utilities."
          (lambda (v) (member v '("fork" "spawn")))
          "System Calls")

  (option 'BIN "/usr/bin"
          "The installation location for the 'no' command"
          (lambda (v) (and (string? v) (file-exists? v)))
          "Paths")

  (option 'LIBEXEC "/usr/libexec/rammel"
          "The installation location of Rammel scripts and configuration files"
          (lambda (v) (and (string? v) (file-exists? v)))
          "Paths")

  (option 'TEXINPUTS "/usr/share/texlive/texmf-local/tex/latex/rammel"
          "The installation location for LaTeX styles and macros (following the TeX Directory Standard)"
          (lambda (v) (string? v))
          "Paths")

  (option 'SHELL "/usr/bin/bash"
          "The shell to use when calling scripts."
          (lambda (v) (and (string? v) (file-exists? v)))
          "Paths")

  (option 'CC "gcc"
          "The name of an ANSI C compiler."
          (lambda (v) (and (string? v) (file-exists? v)))
          "C Compilation")

  (option 'CFLAGS #nil
          "General C compilation flags used througout the entire C build process."
          #nil
          "C Compilation")

  (option 'XCFLAGS #nil
          "Flags used in addition to ``CFLAGS'' when building the ``no'' binary. If your system provides tempnam(3), noweb's indexing will be more efficient if you add -DTEMPNAM to XCFLAGS, which is given to the C compiler."
          #nil
          "C Compilation")

  (option 'LD #nil
          "A C linker-loader."
          #nil
          "C Compilation")

  (option 'LDFLAGS #nil
          "Compilation flags for the linking stage, pased to ``ld''."
          #nil
          "C Compilation")

  (option 'LIBPROLOGUE #nil
          "Options and flags passed to LINKER_LOADER prior to listing libraries; i.e. anything you need to write after listing libraries. It is used like the following: ld $LFLAGS $NOOBJS $LIBPROLOGUE ../cii/libcii ../lua/liblua.so ../lua/liblualibs.so $LIBEPILOGUE."
          #nil
          "C Compilation")

  (option 'LIBEPILOGUE #nil
          "Options and flags passed to LINKER_LOADER after listing libraries; i.e. anything you need to write after listing libraries. It is used like the following: ld $LFLAGS $NOOBJS $LIBPROLOGUE ../cii/libcii ../lua/liblua.so ../lua/liblualibs.so $LIBEPILOGUE."
          #nil
          "C Compilation")

  (option 'AR #nil
          "What to call to build an object-code library. An archiver or bundler tool used to produce object-code libraries from multiple object files; whatever ``ar'' is on your system, or whatever produces object-code libraries like .so or .dll."
          #nil
          "C Compilation")

  (option 'RANLIB #nil
          "How to index an object-code library."
          ;; ranlib is a program for indexing object-code libraries; echo is a fallback.
          (lambda (v) (member v '("ranlib" "echo")))
          "Utilities")

  (option 'CIIMAXALIGN #nil
          "The alignment (in bytes) of pointers returned by malloc; see cii/install.html for more"
          #nil
          "Utilities")

  (option 'XINCLUDES #nil
          #nil
          #nil
          "Utilities")

  (option 'POPEN #nil
          #nil
          #nil
          "Utilities")

  (option 'POSIX #nil
          #nil
          #nil
          "Utilities")

  (option 'STRERROR #nil
          #nil
          #nil
          "Utilities")
#+end_src

#+begin_src makefile
  $(guile $(load "options.scm"))
#+end_src
