* Icon programs
- buildswitch.nw :: An icon implementation of "buildswitch".

* Individual Documents
- doc.nw :: 
- overview.nw :: A document giving an overview of work completed to enhance Noweb 2 leading to the third major version of Noweb.

* C noweb webs
- cargs.nw ::
- columns.nw ::
- cpif.nw ::


** Chapters in a larger document
- env-lua.nw :: Lua registration of the C functions =getenv= and =putenv=.
- errors.nw ::
- fakepretty.nw ::
- finduses.nw ::
- fromascii ::
- fu-run :: the =main= program for /finduses/.
- getline ::
- ipipe ::
- ipipe-lua ::
- lua-help ::
- lua-main ::
- main ::
- markparse ::
- markup ::
- markup-run ::
- match ::
- misc-lua ::
- mnt ::
- modtrees ::
- modules ::
- mpipe ::
- mpipe-lua ::
- mpipe-new ::
- notangle ::
- noweb-lua ::
- nt-run ::
- nullsink ::
- nwbuffer ::
- nwbuffer-lua ::
- nwmtime ::
- nwprocess ::
- nwtime ::
- precompiled ::
- pretty ::
- recognize ::
- stages ::
- strsave ::
- sys ::
- toascii ::
- util ::
- xpipe ::
- xpipe-lua :: 

There's also a version of xpipe in the bugs/ subdirectory.

* Odd LaTeX files
- luatab.nw :: Contains only a documentation chunk, and uses the ~[[...]]~ syntax.

* Confusing files
nocond

* /spawn/, vendored software converted to Noweb

* C directory Makefile
The C directory Makefile is organized as follows:
1. Include nwconfig.
2. Set =CII= and =INCS=, including /C Interfaces and Implementations/ and /Lua/.
   1. Note that after installation of /Noweb 3/, /Noweb 3/ will be used to make "doc" for the semi-literate version of the source code.
   2. ~"-I../../vendor/c-interfaces-and-implementations/include~"
   3. ~"-I../../vendor/lua-5.4.8"~
      1. During the /Lua 2.5/ era an "include" subdirectory was included, not the top level.
         TODO understand how to include modern Lua.
3. =NOOBJS= is a list of all object files required for the =no= target. See the ~NOOBJS~ list.
4. =NWMTIMEOBJS= is a list of all object files required for the =nwmtime= target. See the ~NWMTIMEOBJS~ list.
5. =FILES= is a list of files...
6. C code is distributed alongside the noweb files, which helps with
   bootstrapping. SRCS is a list of C code (.c and .h) which should be
   distributed; whatever .c and .h files are generated should be members of the
   list. A new list, =DIST= will track these files.
7. =NAME= is unused.
8. A metarule is used to control how all =.c.o= objects are compiled, so a new rule isn't needed for every file.
#+begin_src makefile :noweb-ref metarule for compiling C objects
  # metarule so you don't need a new rule for each object file
  .c$(O):;	$(CC) $(INCS) $(XCFLAGS) $(CFLAGS)$@ $*.c
#+end_src

There are no prerequisites for this rule, and the recipe is short so it begins
on the same line. Therefore the syntax of this metarule is ~targets : prerequisites ; recipe~,
with empty prerequisites.

Automatic variables:
-$@ the name of the target
-$* [[https://www.gnu.org/software/make/manual/html_node/Suffix-Rules.html][an old-fashioned suffix-rule]]

** The =nwmtime= target
*** Prerequisites are NWMTIMEOBJS
*** =$(LD) $(LFLAGS)$@ $(NWMTIMEOBJS)=
This rule says to link the named objects together and output the executable =nwmtime=.

#+begin_src bash
  ld -onwmtime columns.o errors.o getline.o nwmtime.o
#+end_src

** The =no= target
*** Prerequisites
#+begin_src bash
  $(NOOBJS) $(LIB3)/cii/memchk.o $(LIB3)/cii/libcii.a $(LUALIB)/liblua.a $(LUALIB)/liblualib.a
#+end_src

*** Recipe
The expansion of various shit is like this.

#+begin_src bash
  ld -ono $(NOOBJS) $(LIBPROLOG) $(LIB3)/cii/libcii. $(LUALIB)/liblua. $(LUALIB)/liblualib. $(LIBEPILOG)
#+end_src

LIBPROLOG is nul, and LIBEPILOG is "-lm".

** The =doc= target
*** Prerequisites, doc.tex and allcode.tex
- doc.tex is a copy of doc.nw
- allcode.tex has a complex recipe
It depends on =$(FILES)=.

#+begin_src bash
  no weave -ifilter "Stages.elide, 'hackers:*'" -n -index $(FILES) > allcode.tex
#+end_src
*** Recipe
=doc.tex= includes =allcode.tex= using the =input= macro.

#+begin_src bash
  pdflatex -output-directory=$(OUTPUT) doc.tex >$(NUL)
  pdflatex -output-directory=$(OUTPUT) doc.tex >$(NUL)
  pdflatex -output-directory=$(OUTPUT) doc.tex
#+end_src
** =DIST=
DIST is a new list of C sources (.c and .h files) that must be distributed alongside the webs.

- =columns.c=
- =columns.h=
- =cpif.c=
- =cpif.h=
- =env-lua.c=
- =env-lua.h=
- =errors.c=
- =errors.h=
- =finduses.c=
- =fromascii.c=
- =fromascii.h=
- =getline.c=
- =getline.h=
- =ipipe-lua.c=
- =ipipe-lua.h=
- =ipipe.c=
- =ipipe.h=
- =lua-help.c=
- =lua-help.h=
- =lua-main.c=
- =lua-main.h=
- =main.c=
- =markparse.c=
- =markparse.h=
- =markup.c=
- =markup.h=
- =match.c=
- =match.h=
- =misc-lua.c=
- =misc-lua.h=
- =modtrees.c=
- =modtrees.h=
- =modules.c=
- =modules.h=
- =mpipe-lua.c=
- =mpipe-lua.h=
- =mpipe.c=
- =mpipe.h=
- =notangle.c=
- =notangle.h=
- =noweb-lua.c=
- =noweb-lua.h=
- =nwbuffer-lua.c=
- =nwbuffer.c=
- =nwbuffer.h=
- =nwmtime.c=
- =nwprocess.c=
- =nwprocess.h=
- =nwtime.c=
- =nwtime.h=
- =precompiled.h=
- =recognize.c=
- =recognize.h=
- =stages.c=
- =stages.h=
- =strsave.c=
- =strsave.h=
- =sys.c=
- =sys.h=
- =util.c=
- =util.h=
- =xpipe-lua.c=
- =xpipe-lua.h=
- =xpipe.c=
- =xpipe.h=

** =FILES=
#+begin_src lua
  files {
    "columns.nw",
    "cpif.nw",
    "errors.nw",
    "finduses.nw",
    "getline.nw",
    "ipipe.nw",
    "ipipe-lua.nw",
    "lua-main.nw",
    "main.nw",
    "markparse.nw",
    "markup.nw",
    "match.nw",
    "modtrees.nw",
    "modules.nw",
    "mpipe.nw",
    "mpipe-lua.nw",
    "notangle.nw",
    "nwbuffer.nw",
    "nwbuffer-lua.nw",
    "nwmtime.nw",
    "nwprocess.nw",
    "nwtime.nw",
    "recognize.nw",
    "strsave.nw",
    "xpipe.nw",
    "xpipe-lua.nw"
  }
#+end_src

** =NOOBJS=
- columns
- cpif
- env-lua
- errors
- finduses
- fromascii
- getline
- ipipe
- ipipe-lua
- lua-help
- lua-main
- main
- markparse
- markup
- misc-lua
- modtrees
- modules
- mpipe
- mpipe-lua
- notangle
- noweb-lua
- nwbuffer
- nwbuffer-lua
- nwprocess
- nwtime
- recognize
- stages
- strsave
- sys
- util
- xpipe
- xpipe-lua

** =NWMTIMEOBJS=
- columns
- errors
- getline
- nwmtime

** Additional rules

A pseudocode implementation of the additional rules as Lua code is given below.

#+begin_src lua
  files = {
    c = {
      "columns",
      "cpif",
      "errors",
      "env-lua",
      "finduses",
      "fromascii",
      "getline",
      "ipipe",
      "ipipe-lua",
      "lua-help",
      "lua-main",
      "main",
      "markup",
      "markparse",
      "misc-lua",
      "modtrees",
      "modules",
      "mpipe",
      "mpipe-lua",
      "notangle",
      "noweb-lua",
      "nwbuffer",
      "nwprocess",
      "nwmtime",
      "nwtime",
      "recognize",
      "stages",
      "strsave",
      "sys",
      "util",
      "xpipe",
      "xpipe-lua"
    },
    h = {
      "cargs",
      "columns",
      "cpif",
      "env-lua",
      "errors",
      "fromascii",
      "getline",
      "ipipe",
      "ipipe-lua",
      "lua-help",
      "lua-main",
      "markparse",
      "markup",
      "match",
      "misc-lua",
      "modtrees",
      "modules",
      "mpipe",
      "mpipe-lua",
      "notangle",
      "noweb-lua",
      "nwbuffer",
      "nwprocess",
      "nwtime",
      "precompiled",
      "recognize",
      "stages",
      "strsave",
      "sys",
      "util",
      "xpipe",
      "xpipe-lua"
    }
  }
  function compile_tangled_c_file (name, header)
    if not header then header = "" else header = "-Rheader" end
    local file, msg = io.open(name, "r")
    if not file then print(msg) end
    string.format([[notangle %s.nw %s -L"#line %%L "\"%s.nw"\"%%N" %S CPIF %s]], name, tangleopts, name, header, name)
  end
  for i in pairs(files["h"]) do compile_tangled_c_file(i, "-Rheader") end
  for i in pairs(files["c"]) do compile_tangled_c_file(i, nil) end

  -- Every key in objects is an object, and each inner table is a list of files
  -- needed for linking that object.
  objects = {
    "columns.o" = { "cargs.h", "columns.c", "columns.h" },
    "cpif.o" = { "cpif.c", "cpif.h", "errors.h", "strsave.h" },
    "env-lua.o" = { "env-lua.c", "env-lua.h", "lua-help.h" },
    "errors.o" = { "errors.c", "errors.h" },
    "finduses.o" = { "errors.h", "finduses.c", "getline.h", "match.h", "nwbuffer.h", "recognize.h" },
    "fromascii.o" = { "errors.h", "fromascii.c", "fromascii.h", "getline.h", "nwbuffer.h" },
    "getline.o" = { "columns.h", "errors.h", "getline.c", "getline.h" },
    "ipipe.o" = { "ipipe.c", "ipipe.h", "nwbuffer.h", "nwtime.h" },
    "ipipe-lua.o" = { "ipipe-lua.c", "ipipe-lua.h" },
    "lua-help.o" = { "lua-help.c", "lua-help.h" },
    "lua-main.o" = { "env-lua.h", "ipipe-lua.h", "lua-main.c", "lua-main.h", "misc-lua.h", "mpipe-lua.h", "noweb-lua.h", "stages.h", "util.h", "xpipe-lua.h" },
    "main.o" = { "cargs.h", "columns.h", "cpif.h", "errors.h", "main.c", "modtrees.h", "modules.h", "notangle.h", "nwbuffer.h" },
    "markparse.o" = { "columns.h", "errors.h", "getline.h", "markparse.c", "markparse.h", "markup.h", "nwbuffer.h" },
    "markup.o" = { "errors.h", "markup.c", "markup.h", "strsave.h" },
    "misc-lua.o" = { "lua-help.h", "misc-lua.c", "misc-lua.h" },
    "modtrees.o" = { "errors.h", "modtrees.c", "modtrees.h", "modules.h", "strsave.h" },
    "modules.o" = { "columns.h", "errors.h", "modtrees.h", "modules.c", "modules.h", "strsave.h" },
    "mpipe.o" = { "fromascii.h", "ipipe.h", "mpipe.c", "mpipe.h", "nwbuffer.h", "xpipe.h" },
    "mpipe-lua.o" = { "lua-help.h", "mpipe.h", "mpipe-lua.c", "mpipe-lua.h" },
    "notangle.o" = { "errors.h", "getline.h", "match.h", "modtrees.h", "modules.h", "notangle.c", "notangle.h", "nwbuffer.h", "strsave.h" },
    "noweb-lua.o" = { "lua-help.h", "noweb-lua.c", "noweb-lua.h", "util.h" },
    "nwbuffer.o" = { "nwbuffer.c", "nwbuffer.h" },
    "nwbuffer-lua.o" = { "lua-help.h", "nwbuffer.h", "nwbuffer-lua.c" },
    "nwmtime.o" = { "getline.h", "nwmtime.c" },
    "nwprocess.o" = { "nwprocess.c", "nwprocess.h" },
    "nwtime.o" = { "nwtime.c", "nwtime.h" },
    "recognize.o" = { "recognize.c" },
    "stages.o" = { "cargs.h", "fromascii.h", "lua-help.h", "markparse.h", "notangle.h", "nwbuffer.h", "stages.c", "stages.h" },
    "strsave.o" = { "errors.h", "strsave.c", "strsave.h" },
    "sys.o" = { "sys.c", "sys.h" },
    "util.o" = { "precompiled.h", "sys.h", "util.c", "util.h" },
    "xpipe.o" = { "errors.h", "nwprocess.h", "sys.h", "util.h", "xpipe.c", "xpipe.h" },
    "xpipe-lua.o" = { "cargs.h", "lua-help.h", "xpipe.h", "xpipe-lua.c", "xpipe-lua.h" }
  }

  for k, t in ipairs(objects) do
    string.format("ld %s %s", o, t)
  end
#+end_src


#+begin_src fundamental
  $(OUTPUT)$(P)cargs.h:       cargs.nw;       $(NOTANGLE) cargs.nw       $(TANGLEOPTS) -L"#line %L "\"cargs.nw"\"%N"       -Rheader $(CPIF) $@
  $(OUTPUT)$(P)columns.h:     columns.nw;     $(NOTANGLE) columns.nw     $(TANGLEOPTS) -L"#line %L "\"columns.nw"\"%N"     -Rheader $(CPIF) $@
  $(OUTPUT)$(P)cpif.h:        cpif.nw;        $(NOTANGLE) cpif.nw        $(TANGLEOPTS) -L"#line %L "\"cpif.nw"\"%N"        -Rheader $(CPIF) $@
  $(OUTPUT)$(P)env-lua.h:     env-lua.nw;     $(NOTANGLE) env-lua.nw     $(TANGLEOPTS) -L"#line %L "\"env-lua.nw"\"%N"     -Rheader $(CPIF) $@
  $(OUTPUT)$(P)errors.h:      errors.nw;      $(NOTANGLE) errors.nw      $(TANGLEOPTS) -L"#line %L "\"errors.nw"\"%N"      -Rheader $(CPIF) $@
  $(OUTPUT)$(P)fromascii.h:   fromascii.nw;   $(NOTANGLE) fromascii.nw   $(TANGLEOPTS) -L"#line %L "\"fromascii.nw"\"%N"   -Rheader $(CPIF) $@
  $(OUTPUT)$(P)getline.h:     getline.nw;     $(NOTANGLE) getline.nw     $(TANGLEOPTS) -L"#line %L "\"getline.nw"\"%N"     -Rheader $(CPIF) $@
  $(OUTPUT)$(P)ipipe.h:       ipipe.nw;       $(NOTANGLE) ipipe.nw       $(TANGLEOPTS) -L"#line %L "\"ipipe.nw"\"%N"       -Rheader $(CPIF) $@
  $(OUTPUT)$(P)ipipe-lua.h:   ipipe-lua.nw;   $(NOTANGLE) ipipe-lua.nw   $(TANGLEOPTS) -L"#line %L "\"ipipe-lua.nw"\"%N"   -Rheader $(CPIF) $@
  $(OUTPUT)$(P)lua-help.h:    lua-help.nw;    $(NOTANGLE) lua-help.nw    $(TANGLEOPTS) -L"#line %L "\"lua-help.nw"\"%N"    -Rheader $(CPIF) $@
  $(OUTPUT)$(P)lua-main.h:    lua-main.nw;    $(NOTANGLE) lua-main.nw    $(TANGLEOPTS) -L"#line %L "\"lua-main.nw"\"%N"    -Rheader $(CPIF) $@
  $(OUTPUT)$(P)markparse.h:   markparse.nw;   $(NOTANGLE) markparse.nw   $(TANGLEOPTS) -L"#line %L "\"markparse.nw"\"%N"   -Rheader $(CPIF) $@
  $(OUTPUT)$(P)markup.h:      markup.nw;      $(NOTANGLE) markup.nw      $(TANGLEOPTS) -L"#line %L "\"markup.nw"\"%N"      -Rheader $(CPIF) $@
  $(OUTPUT)$(P)match.h:       match.nw;       $(NOTANGLE) match.nw       $(TANGLEOPTS) -L"#line %L "\"match.nw"\"%N"       -Rheader $(CPIF) $@
  $(OUTPUT)$(P)misc-lua.h:    misc-lua.nw;    $(NOTANGLE) misc-lua.nw    $(TANGLEOPTS) -L"#line %L "\"misc-lua.nw"\"%N"    -Rheader $(CPIF) $@
  $(OUTPUT)$(P)modtrees.h:    modtrees.nw;    $(NOTANGLE) modtrees.nw    $(TANGLEOPTS) -L"#line %L "\"modtrees.nw"\"%N"    -Rheader $(CPIF) $@
  $(OUTPUT)$(P)modules.h:     modules.nw;     $(NOTANGLE) modules.nw     $(TANGLEOPTS) -L"#line %L "\"modules.nw"\"%N"     -Rheader $(CPIF) $@
  $(OUTPUT)$(P)mpipe.h:       mpipe.nw;       $(NOTANGLE) mpipe.nw       $(TANGLEOPTS) -L"#line %L "\"mpipe.nw"\"%N"       -Rheader $(CPIF) $@
  $(OUTPUT)$(P)mpipe-lua.h:   mpipe-lua.nw;   $(NOTANGLE) mpipe-lua.nw   $(TANGLEOPTS) -L"#line %L "\"mpipe-lua.nw"\"%N"   -Rheader $(CPIF) $@
  $(OUTPUT)$(P)notangle.h:    notangle.nw;    $(NOTANGLE) notangle.nw    $(TANGLEOPTS) -L"#line %L "\"notangle.nw"\"%N"    -Rheader $(CPIF) $@
  $(OUTPUT)$(P)noweb-lua.h:   noweb-lua.nw;   $(NOTANGLE) noweb-lua.nw   $(TANGLEOPTS) -L"#line %L "\"noweb-lua.nw"\"%N"   -Rheader $(CPIF) $@
  $(OUTPUT)$(P)nwbuffer.h:    nwbuffer.nw;    $(NOTANGLE) nwbuffer.nw    $(TANGLEOPTS) -L"#line %L "\"nwbuffer.nw"\"%N"    -Rheader $(CPIF) $@
  $(OUTPUT)$(P)nwprocess.h:   nwprocess.nw;   $(NOTANGLE) nwprocess.nw   $(TANGLEOPTS) -L"#line %L "\"nwprocess.nw"\"%N"   -Rheader $(CPIF) $@
  $(OUTPUT)$(P)nwtime.h:      nwtime.nw;      $(NOTANGLE) nwtime.nw      $(TANGLEOPTS) -L"#line %L "\"nwtime.nw"\"%N"      -Rheader $(CPIF) $@
  $(OUTPUT)$(P)precompiled.h: precompiled.nw; $(NOTANGLE) precompiled.nw $(TANGLEOPTS) -L"#line %L "\"precompiled.nw"\"%N" -Rheader $(CPIF) $@
  $(OUTPUT)$(P)recognize.h:   recognize.nw;   $(NOTANGLE) recognize.nw   $(TANGLEOPTS) -L"#line %L "\"recognize.nw"\"%N"   -Rheader $(CPIF) $@
  $(OUTPUT)$(P)stages.h:      stages.nw;      $(NOTANGLE) stages.nw      $(TANGLEOPTS) -L"#line %L "\"stages.nw"\"%N"      -Rheader $(CPIF) $@
  $(OUTPUT)$(P)strsave.h:     strsave.nw;     $(NOTANGLE) strsave.nw     $(TANGLEOPTS) -L"#line %L "\"strsave.nw"\"%N"     -Rheader $(CPIF) $@
  $(OUTPUT)$(P)sys.h:         sys.nw;         $(NOTANGLE) sys.nw         $(TANGLEOPTS) -L"#line %L "\"sys.nw"\"%N"         -Rheader $(CPIF) $@
  $(OUTPUT)$(P)util.h:        util.nw;        $(NOTANGLE) util.nw        $(TANGLEOPTS) -L"#line %L "\"util.nw"\"%N"        -Rheader $(CPIF) $@
  $(OUTPUT)$(P)xpipe.h:       xpipe.nw;       $(NOTANGLE) xpipe.nw       $(TANGLEOPTS) -L"#line %L "\"xpipe.nw"\"%N"       -Rheader $(CPIF) $@
  $(OUTPUT)$(P)xpipe-lua.h:   xpipe-lua.nw;   $(NOTANGLE) xpipe-lua.nw   $(TANGLEOPTS) -L"#line %L "\"xpipe-lua.nw"\"%N"   -Rheader $(CPIF) $@

  $(OUTPUT)$(P)columns.c:   columns.nw;   $(NOTANGLE) columns.nw   $(TANGLEOPTS) -L"#line %L "\"columns.nw"\"%N"   $(CPIF) $@
  $(OUTPUT)$(P)cpif.c:      cpif.nw;      $(NOTANGLE) cpif.nw      $(TANGLEOPTS) -L"#line %L "\"cpif.nw"\"%N"      $(CPIF) $@
  $(OUTPUT)$(P)errors.c:    errors.nw;    $(NOTANGLE) errors.nw    $(TANGLEOPTS) -L"#line %L "\"errors.nw"\"%N"    $(CPIF) $@
  $(OUTPUT)$(P)env-lua.c:   env-lua.nw;   $(NOTANGLE) env-lua.nw   $(TANGLEOPTS) -L"#line %L "\"env-lua.nw"\"%N"   $(CPIF) $@
  $(OUTPUT)$(P)finduses.c:  finduses.nw;  $(NOTANGLE) finduses.nw  $(TANGLEOPTS) -L"#line %L "\"finduses.nw"\"%N"  $(CPIF) $@
  $(OUTPUT)$(P)fromascii.c: fromascii.nw; $(NOTANGLE) fromascii.nw $(TANGLEOPTS) -L"#line %L "\"fromascii.nw"\"%N" $(CPIF) $@
  $(OUTPUT)$(P)getline.c:   getline.nw;   $(NOTANGLE) getline.nw   $(TANGLEOPTS) -L"#line %L "\"getline.nw"\"%N"   $(CPIF) $@
  $(OUTPUT)$(P)ipipe.c:     ipipe.nw;     $(NOTANGLE) ipipe.nw     $(TANGLEOPTS) -L"#line %L "\"ipipe.nw"\"%N"     $(CPIF) $@
  $(OUTPUT)$(P)ipipe-lua.c: ipipe-lua.nw; $(NOTANGLE) ipipe-lua.nw $(TANGLEOPTS) -L"#line %L "\"ipipe-lua.nw"\"%N" $(CPIF) $@
  $(OUTPUT)$(P)lua-help.c:  lua-help.nw;  $(NOTANGLE) lua-help.nw  $(TANGLEOPTS) -L"#line %L "\"lua-help.nw"\"%N"  $(CPIF) $@
  $(OUTPUT)$(P)lua-main.c:  lua-main.nw;  $(NOTANGLE) lua-main.nw  $(TANGLEOPTS) -L"#line %L "\"lua-main.nw"\"%N"  $(CPIF) $@
  $(OUTPUT)$(P)main.c:      main.nw;      $(NOTANGLE) main.nw      $(TANGLEOPTS) -L"#line %L "\"main.nw"\"%N"      $(CPIF) $@
  $(OUTPUT)$(P)markup.c:    markup.nw;    $(NOTANGLE) markup.nw    $(TANGLEOPTS) -L"#line %L "\"markup.nw"\"%N"    $(CPIF) $@
  $(OUTPUT)$(P)markparse.c: markparse.nw; $(NOTANGLE) markparse.nw $(TANGLEOPTS) -L"#line %L "\"markparse.nw"\"%N" $(CPIF) $@
  $(OUTPUT)$(P)misc-lua.c:  misc-lua.nw;  $(NOTANGLE) misc-lua.nw  $(TANGLEOPTS) -L"#line %L "\"misc-lua.nw"\"%N"  $(CPIF) $@
  $(OUTPUT)$(P)modtrees.c:  modtrees.nw;  $(NOTANGLE) modtrees.nw  $(TANGLEOPTS) -L"#line %L "\"modtrees.nw"\"%N"  $(CPIF) $@
  $(OUTPUT)$(P)modules.c:   modules.nw;   $(NOTANGLE) modules.nw   $(TANGLEOPTS) -L"#line %L "\"modules.nw"\"%N"   $(CPIF) $@
  $(OUTPUT)$(P)mpipe.c:     mpipe.nw;     $(NOTANGLE) mpipe.nw     $(TANGLEOPTS) -L"#line %L "\"mpipe.nw"\"%N"     $(CPIF) $@
  $(OUTPUT)$(P)mpipe-lua.c: mpipe-lua.nw; $(NOTANGLE) mpipe-lua.nw $(TANGLEOPTS) -L"#line %L "\"mpipe-lua.nw"\"%N" $(CPIF) $@
  $(OUTPUT)$(P)notangle.c:  notangle.nw;  $(NOTANGLE) notangle.nw  $(TANGLEOPTS) -L"#line %L "\"notangle.nw"\"%N"  $(CPIF) $@
  $(OUTPUT)$(P)noweb-lua.c: noweb-lua.nw; $(NOTANGLE) noweb-lua.nw $(TANGLEOPTS) -L"#line %L "\"noweb-lua.nw"\"%N" $(CPIF) $@
  $(OUTPUT)$(P)nwbuffer.c:  nwbuffer.nw;  $(NOTANGLE) nwbuffer.nw  $(TANGLEOPTS) -L"#line %L "\"nwbuffer.nw"\"%N"  $(CPIF) $@
  $(OUTPUT)$(P)nwprocess.c: nwprocess.nw; $(NOTANGLE) nwprocess.nw $(TANGLEOPTS) -L"#line %L "\"nwprocess.nw"\"%N" $(CPIF) $@
  $(OUTPUT)$(P)nwmtime.c:   nwmtime.nw;   $(NOTANGLE) nwmtime.nw   $(TANGLEOPTS) -L"#line %L "\"nwmtime.nw"\"%N"   $(CPIF) $@
  $(OUTPUT)$(P)nwtime.c:    nwtime.nw;    $(NOTANGLE) nwtime.nw    $(TANGLEOPTS) -L"#line %L "\"nwtime.nw"\"%N"    $(CPIF) $@
  $(OUTPUT)$(P)recognize.c: recognize.nw; $(NOTANGLE) recognize.nw $(TANGLEOPTS) -L"#line %L "\"recognize.nw"\"%N" $(CPIF) $@
  $(OUTPUT)$(P)stages.c:    stages.nw;    $(NOTANGLE) stages.nw    $(TANGLEOPTS) -L"#line %L "\"stages.nw"\"%N"    $(CPIF) $@
  $(OUTPUT)$(P)strsave.c:   strsave.nw;   $(NOTANGLE) strsave.nw   $(TANGLEOPTS) -L"#line %L "\"strsave.nw"\"%N"   $(CPIF) $@
  $(OUTPUT)$(P)sys.c:       sys.nw;       $(NOTANGLE) sys.nw       $(TANGLEOPTS) -L"#line %L "\"sys.nw"\"%N"       $(CPIF) $@
  $(OUTPUT)$(P)util.c:      util.nw;      $(NOTANGLE) util.nw      $(TANGLEOPTS) -L"#line %L "\"util.nw"\"%N"      $(CPIF) $@
  $(OUTPUT)$(P)xpipe.c:     xpipe.nw;     $(NOTANGLE) xpipe.nw     $(TANGLEOPTS) -L"#line %L "\"xpipe.nw"\"%N"     $(CPIF) $@
  $(OUTPUT)$(P)xpipe-lua.c: xpipe-lua.nw; $(NOTANGLE) xpipe-lua.nw $(TANGLEOPTS) -L"#line %L "\"xpipe-lua.nw"\"%N" $(CPIF) $@

  $(OUTPUT)$(P)nwbuffer-lua.0: nwbuffer-lua.nw
      $(NOTANGLE) nwbuffer-lua.nw $(TANGLEOPTS) -R"key macros header" >$(OUTPUT)$(P)nwbuffer-lua.0
  $(OUTPUT)$(P)nwbuffer-lua.1: nwbuffer.nw
      $(NOTANGLE) nwbuffer.nw $(TANGLEOPTS) -R"key macros" >$(OUTPUT)$(P)nwbuffer-lua.1
  $(OUTPUT)$(P)nwbuffer-lua.2: nwbuffer-lua.nw
      $(NOTANGLE) nwbuffer-lua.nw $(TANGLEOPTS) -R"key macros footer" >$(OUTPUT)$(P)nwbuffer-lua.2
  $(OUTPUT)$(P)nwbuffer-lua.3: $(OUTPUT)$(P)nwbuffer-lua.0 $(OUTPUT)$(P)nwbuffer-lua.1 $(OUTPUT)$(P)nwbuffer-lua.2
      more $(OUTPUT)$(P)nwbuffer-lua.0 | $(TOOLS)$(P)tie $(OUTPUT)$(P)nwbuffer-lua.1 $(OUTPUT)$(P)nwbuffer-lua.2 nwbuffer-lua.nw >$(OUTPUT)$(P)nwbuffer-lua.3
  $(OUTPUT)$(P)nwbuffer-lua.c: $(OUTPUT)$(P)nwbuffer-lua.3
      $(NOTANGLE) $(OUTPUT)$(P)nwbuffer-lua.3 $(TANGLEOPTS) $(CPIF) $@

  $(OUTPUT)$(P)columns$(O):      $(OUTPUT)$(P)cargs.h $(OUTPUT)$(P)columns.c $(OUTPUT)$(P)columns.h
  $(OUTPUT)$(P)cpif$(O):         $(OUTPUT)$(P)cpif.c $(OUTPUT)$(P)cpif.h $(OUTPUT)$(P)errors.h $(OUTPUT)$(P)strsave.h
  $(OUTPUT)$(P)env-lua$(O):      $(OUTPUT)$(P)env-lua.c $(OUTPUT)$(P)env-lua.h $(OUTPUT)$(P)lua-help.h
  $(OUTPUT)$(P)errors$(O):       $(OUTPUT)$(P)errors.c $(OUTPUT)$(P)errors.h
  $(OUTPUT)$(P)finduses$(O):     $(OUTPUT)$(P)errors.h $(OUTPUT)$(P)finduses.c $(OUTPUT)$(P)getline.h $(OUTPUT)$(P)match.h $(OUTPUT)$(P)nwbuffer.h $(OUTPUT)$(P)recognize.h
  $(OUTPUT)$(P)fromascii$(O):    $(OUTPUT)$(P)errors.h $(OUTPUT)$(P)fromascii.c $(OUTPUT)$(P)fromascii.h $(OUTPUT)$(P)getline.h $(OUTPUT)$(P)nwbuffer.h
  $(OUTPUT)$(P)getline$(O):      $(OUTPUT)$(P)columns.h $(OUTPUT)$(P)errors.h $(OUTPUT)$(P)getline.c $(OUTPUT)$(P)getline.h
  $(OUTPUT)$(P)ipipe$(O):        $(OUTPUT)$(P)ipipe.c $(OUTPUT)$(P)ipipe.h $(OUTPUT)$(P)nwbuffer.h $(OUTPUT)$(P)nwtime.h
  $(OUTPUT)$(P)ipipe-lua$(O):    $(OUTPUT)$(P)ipipe-lua.c $(OUTPUT)$(P)ipipe-lua.h
  $(OUTPUT)$(P)lua-help$(O):     $(OUTPUT)$(P)lua-help.c $(OUTPUT)$(P)lua-help.h
  $(OUTPUT)$(P)lua-main$(O):     $(OUTPUT)$(P)env-lua.h $(OUTPUT)$(P)ipipe-lua.h $(OUTPUT)$(P)lua-main.c $(OUTPUT)$(P)lua-main.h $(OUTPUT)$(P)misc-lua.h $(OUTPUT)$(P)mpipe-lua.h $(OUTPUT)$(P)noweb-lua.h $(OUTPUT)$(P)stages.h $(OUTPUT)$(P)util.h $(OUTPUT)$(P)xpipe-lua.h
  $(OUTPUT)$(P)main$(O):         $(OUTPUT)$(P)cargs.h $(OUTPUT)$(P)columns.h $(OUTPUT)$(P)cpif.h $(OUTPUT)$(P)errors.h $(OUTPUT)$(P)main.c $(OUTPUT)$(P)modtrees.h $(OUTPUT)$(P)modules.h $(OUTPUT)$(P)notangle.h $(OUTPUT)$(P)nwbuffer.h
  $(OUTPUT)$(P)markparse$(O):    $(OUTPUT)$(P)columns.h $(OUTPUT)$(P)errors.h $(OUTPUT)$(P)getline.h $(OUTPUT)$(P)markparse.c $(OUTPUT)$(P)markparse.h $(OUTPUT)$(P)markup.h $(OUTPUT)$(P)nwbuffer.h
  $(OUTPUT)$(P)markup$(O):       $(OUTPUT)$(P)errors.h $(OUTPUT)$(P)markup.c $(OUTPUT)$(P)markup.h $(OUTPUT)$(P)strsave.h
  $(OUTPUT)$(P)misc-lua$(O):     $(OUTPUT)$(P)lua-help.h $(OUTPUT)$(P)misc-lua.c $(OUTPUT)$(P)misc-lua.h
  $(OUTPUT)$(P)modtrees$(O):     $(OUTPUT)$(P)errors.h $(OUTPUT)$(P)modtrees.c $(OUTPUT)$(P)modtrees.h $(OUTPUT)$(P)modules.h $(OUTPUT)$(P)strsave.h
  $(OUTPUT)$(P)modules$(O):      $(OUTPUT)$(P)columns.h $(OUTPUT)$(P)errors.h $(OUTPUT)$(P)modtrees.h $(OUTPUT)$(P)modules.c $(OUTPUT)$(P)modules.h $(OUTPUT)$(P)strsave.h
  $(OUTPUT)$(P)mpipe$(O):        $(OUTPUT)$(P)fromascii.h $(OUTPUT)$(P)ipipe.h $(OUTPUT)$(P)mpipe.c $(OUTPUT)$(P)mpipe.h $(OUTPUT)$(P)nwbuffer.h $(OUTPUT)$(P)xpipe.h
  $(OUTPUT)$(P)mpipe-lua$(O):    $(OUTPUT)$(P)lua-help.h $(OUTPUT)$(P)mpipe.h $(OUTPUT)$(P)mpipe-lua.c $(OUTPUT)$(P)mpipe-lua.h
  $(OUTPUT)$(P)notangle$(O):     $(OUTPUT)$(P)errors.h $(OUTPUT)$(P)getline.h $(OUTPUT)$(P)match.h $(OUTPUT)$(P)modtrees.h $(OUTPUT)$(P)modules.h $(OUTPUT)$(P)notangle.c $(OUTPUT)$(P)notangle.h $(OUTPUT)$(P)nwbuffer.h $(OUTPUT)$(P)strsave.h
  $(OUTPUT)$(P)noweb-lua$(O):    $(OUTPUT)$(P)lua-help.h $(OUTPUT)$(P)noweb-lua.c $(OUTPUT)$(P)noweb-lua.h $(OUTPUT)$(P)util.h
  $(OUTPUT)$(P)nwbuffer$(O):     $(OUTPUT)$(P)nwbuffer.c $(OUTPUT)$(P)nwbuffer.h
  $(OUTPUT)$(P)nwbuffer-lua$(O): $(OUTPUT)$(P)lua-help.h $(OUTPUT)$(P)nwbuffer.h $(OUTPUT)$(P)nwbuffer-lua.c
  $(OUTPUT)$(P)nwmtime$(O):      $(OUTPUT)$(P)getline.h $(OUTPUT)$(P)nwmtime.c
  $(OUTPUT)$(P)nwprocess$(O):    $(OUTPUT)$(P)nwprocess.c $(OUTPUT)$(P)nwprocess.h
  $(OUTPUT)$(P)nwtime$(O):       $(OUTPUT)$(P)nwtime.c $(OUTPUT)$(P)nwtime.h
  $(OUTPUT)$(P)recognize$(O):    $(OUTPUT)$(P)recognize.c
  $(OUTPUT)$(P)stages$(O):       $(OUTPUT)$(P)cargs.h $(OUTPUT)$(P)fromascii.h $(OUTPUT)$(P)lua-help.h $(OUTPUT)$(P)markparse.h $(OUTPUT)$(P)notangle.h $(OUTPUT)$(P)nwbuffer.h $(OUTPUT)$(P)stages.c $(OUTPUT)$(P)stages.h
  $(OUTPUT)$(P)strsave$(O):      $(OUTPUT)$(P)errors.h $(OUTPUT)$(P)strsave.c $(OUTPUT)$(P)strsave.h
  $(OUTPUT)$(P)sys$(O):          $(OUTPUT)$(P)sys.c $(OUTPUT)$(P)sys.h
  $(OUTPUT)$(P)util$(O):         $(OUTPUT)$(P)precompiled.h $(OUTPUT)$(P)sys.h $(OUTPUT)$(P)util.c $(OUTPUT)$(P)util.h
  $(OUTPUT)$(P)xpipe$(O):        $(OUTPUT)$(P)errors.h $(OUTPUT)$(P)nwprocess.h $(OUTPUT)$(P)sys.h $(OUTPUT)$(P)util.h $(OUTPUT)$(P)xpipe.c $(OUTPUT)$(P)xpipe.h
  $(OUTPUT)$(P)xpipe-lua$(O):    $(OUTPUT)$(P)cargs.h $(OUTPUT)$(P)lua-help.h $(OUTPUT)$(P)xpipe.h $(OUTPUT)$(P)xpipe-lua.c $(OUTPUT)$(P)xpipe-lua.h
#+end_src
